# Generated by Django 5.0.3 on 2024-06-05 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DEPARTAMENTOS',
            fields=[
                ('iddepartamento', models.IntegerField(db_column='idDepartamentos', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ELECTRONICA_RED',
            fields=[
                ('idelectronica_red', models.IntegerField(db_column='idElectronica_red', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('modelo', models.CharField(db_column='Modelo', max_length=45)),
                ('tipo', models.CharField(db_column='Tipo', max_length=45)),
                ('puertos', models.IntegerField(blank=True, db_column='Puertos', null=True)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TARJETAS',
            fields=[
                ('idtarjeta', models.IntegerField(db_column='idTarjetas', primary_key=True, serialize=False)),
                ('num_tarjeta', models.CharField(db_column='Num_Tarjeta', max_length=45, unique=True)),
                ('estado', models.CharField(db_column='Estado', max_length=45)),
                ('observacion', models.CharField(blank=True, db_column='Observaciones', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EMPLEADOS',
            fields=[
                ('idempleado', models.IntegerField(db_column='idEmpleado', primary_key=True, serialize=False)),
                ('usuario', models.CharField(db_column='Usuario', max_length=45, unique=True)),
                ('dni', models.CharField(db_column='DNI', max_length=10, unique=True)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('apellidos', models.CharField(db_column='Apellidos', max_length=50)),
                ('email', models.CharField(db_column='Email', max_length=50, unique=True)),
                ('fecha_alta', models.DateField(db_column='Fecha_alta')),
                ('fecha_baja', models.DateField(db_column='Fecha_baja')),
                ('estado', models.CharField(db_column='Estado', max_length=45)),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('REMOTO', 'Remoto'), ('HIBRIDO', 'Híbrido')], db_column='Modalidad', max_length=45)),
                ('ordenador1', models.CharField(choices=[('Lenovo ThinkPad E14', 'Lenovo ThinkPad E14'), ('Lenovo ThinkPad E15', 'Lenovo ThinkPad E15'), ('Chromebook', 'Chromebook'), ('NONE', 'NONE')], db_column='Ordenador1', max_length=90)),
                ('ordenador2', models.CharField(choices=[('Lenovo ThinkPad E14', 'Lenovo ThinkPad E14'), ('Lenovo ThinkPad E15', 'Lenovo ThinkPad E15'), ('Chromebook', 'Chromebook'), ('NONE', 'NONE')], db_column='Ordenador2', max_length=90)),
                ('ordenador3', models.CharField(choices=[('Lenovo ThinkPad E14', 'Lenovo ThinkPad E14'), ('Lenovo ThinkPad E15', 'Lenovo ThinkPad E15'), ('Chromebook', 'Chromebook'), ('NONE', 'NONE')], db_column='Ordenador3', max_length=90)),
                ('entrada_cpd', models.IntegerField(db_column='Entrada_CPD')),
                ('llave_acceso', models.IntegerField(db_column='Llave_acceso')),
                ('homy_hub_parking', models.IntegerField(db_column='Homy_Hub_Parking')),
                ('pub_key_pgp', models.CharField(blank=True, db_column='Pub_Key_PGP', max_length=20, null=True, unique=True)),
                ('departamento', models.ForeignKey(db_column='Departamento', on_delete=django.db.models.deletion.DO_NOTHING, to='tfg2.departamentos', to_field='nombre')),
                ('responsable', models.ForeignKey(blank=True, db_column='Responsable', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tfg2.empleados', to_field='usuario')),
                ('tarjeta', models.ForeignKey(blank=True, db_column='Tarjeta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tfg2.tarjetas', to_field='num_tarjeta')),
            ],
        ),
        migrations.CreateModel(
            name='DISPOSITIVOS_EXTERNOS',
            fields=[
                ('iddispositivo_externo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45, unique=True)),
                ('modelo', models.CharField(db_column='Modelo', max_length=45)),
                ('numero_serie', models.CharField(db_column='Numero_serie', max_length=45, unique=True)),
                ('capacidad', models.CharField(blank=True, db_column='Capacidad', max_length=45, null=True)),
                ('tipo', models.CharField(blank=True, db_column='Tipo', max_length=45, null=True)),
                ('carcasa', models.CharField(blank=True, db_column='Carcasa', max_length=45, null=True)),
                ('nivel_criticidad_info', models.CharField(blank=True, db_column='Nivel_criticidad_info', max_length=45, null=True)),
                ('etiquetado', models.CharField(blank=True, db_column='Etiquetado', max_length=45, null=True)),
                ('función', models.CharField(blank=True, db_column='Función', max_length=30, null=True)),
                ('departamento', models.ForeignKey(db_column='Departamento', on_delete=django.db.models.deletion.DO_NOTHING, to='tfg2.departamentos', to_field='nombre')),
                ('usuario', models.ForeignKey(db_column='Usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='tfg2.empleados', to_field='usuario')),
            ],
        ),
        migrations.CreateModel(
            name='MOVILES',
            fields=[
                ('idmovil', models.IntegerField(db_column='idMoviles', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45, unique=True)),
                ('sim', models.IntegerField(blank=True, db_column='SIM', null=True)),
                ('numero_telefono', models.IntegerField(blank=True, db_column='Numero_telefono', null=True)),
                ('estado', models.CharField(db_column='Estado', max_length=45)),
                ('terminal', models.CharField(db_column='Terminal', max_length=45)),
                ('modelo', models.CharField(blank=True, db_column='Modelo', max_length=45, null=True)),
                ('numero_serie', models.CharField(blank=True, db_column='Numero_Serie', max_length=45, null=True, unique=True)),
                ('tipo', models.CharField(db_column='Tipo', max_length=45)),
                ('usuario', models.ForeignKey(blank=True, db_column='Usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tfg2.empleados', to_field='usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ORDENADORES',
            fields=[
                ('idordenador', models.IntegerField(db_column='idOrdenador', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45, unique=True)),
                ('estado', models.CharField(db_column='Estado', max_length=45)),
                ('equipo', models.CharField(choices=[('Lenovo ThinkPad E14', 'Lenovo ThinkPad E14'), ('Lenovo ThinkPad E15', 'Lenovo ThinkPad E15'), ('Chromebook', 'Chromebook'), ('NONE', 'NONE')], db_column='Equipo', max_length=90)),
                ('numero_serie', models.CharField(db_column='Numero_serie', max_length=45, unique=True)),
                ('modelo', models.CharField(blank=True, db_column='Modelo', max_length=45, null=True)),
                ('tipo', models.CharField(blank=True, db_column='Tipo', max_length=45, null=True)),
                ('cpu', models.CharField(blank=True, db_column='CPU', max_length=45, null=True)),
                ('memoria', models.CharField(blank=True, db_column='Memoria', max_length=45, null=True)),
                ('ubicacion', models.CharField(db_column='Ubicacion', max_length=45)),
                ('usuario', models.ForeignKey(db_column='usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='tfg2.empleados', to_field='usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PERIFERICOS',
            fields=[
                ('idperiferico', models.IntegerField(db_column='idPerifericos', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=45)),
                ('usuario', models.ForeignKey(blank=True, db_column='Usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tfg2.empleados', to_field='usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PUESTOS_TRABAJOS',
            fields=[
                ('nombre', models.CharField(db_column='Nombre', max_length=45, primary_key=True, serialize=False, unique=True)),
                ('departamento', models.ForeignKey(db_column='Departamento', on_delete=django.db.models.deletion.DO_NOTHING, to='tfg2.departamentos', to_field='nombre')),
            ],
        ),
        migrations.AddField(
            model_name='empleados',
            name='puesto',
            field=models.ForeignKey(db_column='Puesto', on_delete=django.db.models.deletion.DO_NOTHING, to='tfg2.puestos_trabajos'),
        ),
        migrations.CreateModel(
            name='SERVICIOS',
            fields=[
                ('idservicio', models.IntegerField(db_column='idServicios', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50, unique=True)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=200)),
                ('bastidor', models.CharField(blank=True, db_column='Bastidor', max_length=45, null=True)),
                ('tipo', models.CharField(db_column='Tipo', max_length=45)),
                ('proveedor', models.CharField(blank=True, db_column='Proveedor', max_length=45, null=True)),
                ('observaciones', models.CharField(blank=True, db_column='Observaciones', max_length=200, null=True)),
                ('propietario', models.ForeignKey(db_column='Propietario', default='mmanteca', on_delete=django.db.models.deletion.DO_NOTHING, to='tfg2.empleados', to_field='usuario')),
                ('responsable', models.ForeignKey(db_column='Responsable', default='jortega', on_delete=django.db.models.deletion.DO_NOTHING, related_name='servicios_responsable_set', to='tfg2.empleados', to_field='usuario')),
            ],
        ),
        migrations.CreateModel(
            name='INCIDENCIAS_TARJETAS',
            fields=[
                ('num_tarjeta', models.ForeignKey(db_column='num_tarjeta', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tfg2.tarjetas', to_field='num_tarjeta')),
                ('incidencia', models.CharField(db_column='Incidencia', max_length=200)),
                ('usuario', models.ForeignKey(db_column='usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='tfg2.empleados', to_field='usuario')),
            ],
        ),
    ]
