# Generated by Django 5.0.3 on 2024-06-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('BAJA', 'BAJA'), ('DESPEDIDO', 'DESPEDIDO')], db_column='Estado', max_length=45),
        ),
    ]
