# Generated by Django 5.0.3 on 2024-06-05 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg2', '0002_alter_empleados_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenadores',
            name='equipo',
            field=models.CharField(choices=[('Lenovo ThinkPad E14', 'Lenovo ThinkPad E14'), ('Lenovo ThinkPad E15', 'Lenovo ThinkPad E15'), ('Chromebook', 'Chromebook')], db_column='Equipo', max_length=90),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='bastidor',
            field=models.CharField(choices=[('COMUNICACIONES', 'COMUNICACIONES'), ('SEGURIDAD', 'SEGURIDAD'), ('NONE', 'NONE')], db_column='Bastidor', max_length=45),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='propietario',
            field=models.ForeignKey(db_column='Propietario', default='jcuellar', on_delete=django.db.models.deletion.DO_NOTHING, to='tfg2.empleados', to_field='usuario'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='responsable',
            field=models.ForeignKey(db_column='Responsable', default='earmani', on_delete=django.db.models.deletion.DO_NOTHING, related_name='servicios_responsable_set', to='tfg2.empleados', to_field='usuario'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='tipo',
            field=models.CharField(choices=[('CLOUD', 'CLOUD'), ('FISICO', 'FISICO')], db_column='Tipo', max_length=45),
        ),
        migrations.AlterField(
            model_name='tarjetas',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'ACTIVA'), ('ASIGNADA', 'ASIGNADA'), ('PERDIDA', 'PERDIDA')], db_column='Estado', max_length=45),
        ),
    ]
